# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ghost_messenger.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(642, 793)
        font = QtGui.QFont()
        font.setPointSize(20)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.NameMessenger = QtWidgets.QLabel(self.centralwidget)
        self.NameMessenger.setGeometry(QtCore.QRect(90, 10, 291, 41))
        font = QtGui.QFont()
        font.setFamily("MS PGothic")
        self.NameMessenger.setFont(font)
        self.NameMessenger.setTextFormat(QtCore.Qt.PlainText)
        self.NameMessenger.setObjectName("NameMessenger")
        self.BatPicture = QtWidgets.QLabel(self.centralwidget)
        self.BatPicture.setEnabled(True)
        self.BatPicture.setGeometry(QtCore.QRect(440, 10, 181, 121))
        self.BatPicture.setObjectName("BatPicture")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setEnabled(True)
        self.textBrowser.setGeometry(QtCore.QRect(20, 140, 601, 561))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.NoAntialias)
        self.textBrowser.setFont(font)
        self.textBrowser.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.textBrowser.setAcceptDrops(True)
        self.textBrowser.setObjectName("textBrowser")
        self.NameEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.NameEdit.setGeometry(QtCore.QRect(20, 100, 401, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.NameEdit.setFont(font)
        self.NameEdit.setText("")
        self.NameEdit.setObjectName("NameEdit")
        self.UsersNumber = QtWidgets.QLCDNumber(self.centralwidget)
        self.UsersNumber.setGeometry(QtCore.QRect(130, 60, 51, 23))
        self.UsersNumber.setObjectName("UsersNumber")
        self.MessagesNumber = QtWidgets.QLCDNumber(self.centralwidget)
        self.MessagesNumber.setGeometry(QtCore.QRect(370, 60, 51, 23))
        self.MessagesNumber.setObjectName("MessagesNumber")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 55, 71, 31))
        font = QtGui.QFont()
        font.setFamily("MS PGothic")
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setTextFormat(QtCore.Qt.PlainText)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(240, 55, 111, 31))
        font = QtGui.QFont()
        font.setFamily("MS PGothic")
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setTextFormat(QtCore.Qt.PlainText)
        self.label_4.setObjectName("label_4")
        self.messegeEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.messegeEdit.setGeometry(QtCore.QRect(20, 710, 531, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.messegeEdit.setFont(font)
        self.messegeEdit.setText("")
        self.messegeEdit.setObjectName("messegeEdit")
        self.GoButton = QtWidgets.QPushButton(self.centralwidget)
        self.GoButton.setGeometry(QtCore.QRect(560, 710, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.GoButton.setFont(font)
        self.GoButton.setObjectName("GoButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.NameMessenger.setText(_translate("MainWindow", "Ghost messenger"))
        self.BatPicture.setText(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:20pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><img src=\":/newPrefix/bat.jpg\" /></p></body></html>"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.NameEdit.setPlaceholderText(_translate("MainWindow", "Введите имя пользователя..."))
        self.label_3.setText(_translate("MainWindow", "Users:"))
        self.label_4.setText(_translate("MainWindow", "Messages:"))
        self.messegeEdit.setPlaceholderText(_translate("MainWindow", "Введите текст сообщения..."))
        self.GoButton.setText(_translate("MainWindow", "Go"))
import resimg_rc
